export type Event =
  | 'INIT'
  | 'SHARE_VIA_WHATSAPP'
  | 'SHARE_VIA_FACEBOOK'
  | 'SHARE_VIA_TWITTER'
  | 'OPEN_SOURCE'
  | 'SELECT_STATE'
  | 'GO_TO_HOME'
  | 'SET_DAILY_MODE'
  | 'SET_HISTORICAL_MODE';
