const informationByState = {
  AGUASCALIENTES: {
    confirmed: 0,
    negatives: 0,
    suspects: 0,
    deaths: 0,
    actives: 0,
  },
  'BAJA CALIFORNIA': {
    confirmed: 0,
    negatives: 0,
    suspects: 0,
    deaths: 0,
    actives: 0,
  },
  'BAJA CALIFORNIA SUR': {
    confirmed: 0,
    negatives: 0,
    suspects: 0,
    deaths: 0,
    actives: 0,
  },
  CAMPECHE: {
    confirmed: 0,
    negatives: 0,
    suspects: 0,
    deaths: 0,
    actives: 0,
  },
  'COAHUILA DE ZARAGOZA': {
    confirmed: 0,
    negatives: 0,
    suspects: 0,
    deaths: 0,
    actives: 0,
  },
  COLIMA: {
    confirmed: 0,
    negatives: 0,
    suspects: 0,
    deaths: 0,
    actives: 0,
  },
  CHIAPAS: {
    confirmed: 0,
    negatives: 0,
    suspects: 0,
    deaths: 0,
    actives: 0,
  },
  CHIHUAHUA: {
    confirmed: 0,
    negatives: 0,
    suspects: 0,
    deaths: 0,
    actives: 0,
  },
  'CIUDAD DE MÉXICO': {
    confirmed: 0,
    negatives: 0,
    suspects: 0,
    deaths: 0,
    actives: 0,
  },
  DURANGO: {
    confirmed: 0,
    negatives: 0,
    suspects: 0,
    deaths: 0,
    actives: 0,
  },
  GUANAJUATO: {
    confirmed: 0,
    negatives: 0,
    suspects: 0,
    deaths: 0,
    actives: 0,
  },
  GUERRERO: {
    confirmed: 0,
    negatives: 0,
    suspects: 0,
    deaths: 0,
    actives: 0,
  },
  HIDALGO: {
    confirmed: 0,
    negatives: 0,
    suspects: 0,
    deaths: 0,
    actives: 0,
  },
  JALISCO: {
    confirmed: 0,
    negatives: 0,
    suspects: 0,
    deaths: 0,
    actives: 0,
  },
  MÉXICO: {
    confirmed: 0,
    negatives: 0,
    suspects: 0,
    deaths: 0,
    actives: 0,
  },
  'MICHOACÁN DE OCAMPO': {
    confirmed: 0,
    negatives: 0,
    suspects: 0,
    deaths: 0,
    actives: 0,
  },
  MORELOS: {
    confirmed: 0,
    negatives: 0,
    suspects: 0,
    deaths: 0,
    actives: 0,
  },
  NAYARIT: {
    confirmed: 0,
    negatives: 0,
    suspects: 0,
    deaths: 0,
    actives: 0,
  },
  'NUEVO LEÓN': {
    confirmed: 0,
    negatives: 0,
    suspects: 0,
    deaths: 0,
    actives: 0,
  },
  OAXACA: {
    confirmed: 0,
    negatives: 0,
    suspects: 0,
    deaths: 0,
    actives: 0,
  },
  PUEBLA: {
    confirmed: 0,
    negatives: 0,
    suspects: 0,
    deaths: 0,
    actives: 0,
  },
  QUERÉTARO: {
    confirmed: 0,
    negatives: 0,
    suspects: 0,
    deaths: 0,
    actives: 0,
  },
  'QUINTANA ROO': {
    confirmed: 0,
    negatives: 0,
    suspects: 0,
    deaths: 0,
    actives: 0,
  },
  'SAN LUIS POTOSÍ': {
    confirmed: 0,
    negatives: 0,
    suspects: 0,
    deaths: 0,
    actives: 0,
  },
  SINALOA: {
    confirmed: 0,
    negatives: 0,
    suspects: 0,
    deaths: 0,
    actives: 0,
  },
  SONORA: {
    confirmed: 0,
    negatives: 0,
    suspects: 0,
    deaths: 0,
    actives: 0,
  },
  TABASCO: {
    confirmed: 0,
    negatives: 0,
    suspects: 0,
    deaths: 0,
    actives: 0,
  },
  TAMAULIPAS: {
    confirmed: 0,
    negatives: 0,
    suspects: 0,
    deaths: 0,
    actives: 0,
  },
  TLAXCALA: {
    confirmed: 0,
    negatives: 0,
    suspects: 0,
    deaths: 0,
    actives: 0,
  },
  'VERACRUZ DE IGNACIO DE LA LLAVE': {
    confirmed: 0,
    negatives: 0,
    suspects: 0,
    deaths: 0,
    actives: 0,
  },
  YUCATÁN: {
    confirmed: 0,
    negatives: 0,
    suspects: 0,
    deaths: 0,
    actives: 0,
  },
  ZACATECAS: {
    confirmed: 0,
    negatives: 0,
    suspects: 0,
    deaths: 0,
    actives: 0,
  },
  'ESTADOS UNIDOS MEXICANOS': {
    confirmed: 0,
    negatives: 0,
    suspects: 0,
    deaths: 0,
    actives: 0,
  },
  'NO APLICA': {
    confirmed: 0,
    negatives: 0,
    suspects: 0,
    deaths: 0,
    actives: 0,
  },
  'SE IGNORA': {
    confirmed: 0,
    negatives: 0,
    suspects: 0,
    deaths: 0,
    actives: 0,
  },
  'NO ESPECIFICADO': {
    confirmed: 0,
    negatives: 0,
    suspects: 0,
    deaths: 0,
    actives: 0,
  },
  DESCONOCIDO: {
    confirmed: 0,
    negatives: 0,
    suspects: 0,
    deaths: 0,
    actives: 0,
  },
};

module.exports = {
  informationByState,
};
